# Generated by Django 4.1 on 2024-07-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='description',
            new_name='Description',
        ),
    ]
